services:
  - type: web
    name: work-manager
    env: node
    plan: free
    buildCommand: ""
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: ADMIN_ID
        value: cypher
      - key: ADMIN_PASSWORD
        sync: false
      - key: MEMBER_ID
        value: jaguar
      - key: MEMBER_PASSWORD
        sync: false
